### ISSUE TITLE
🚀 [EPIC] Release v1.6

### ISSUE THREAD

**Issue by AdrievandeVreede** [EPieter/Natural_Selection#17]
Features/improvements:
- [x] Different languages available
~~Automatic update game~~ moved to the version 2.0
- [x] Settings menu #20
- [x] Bitcoin and diamond should be an investment #29
- [x] Install game from internet #30
- [x] Change currency's #39
- [x] Different states available

Info:
- [x] Testing
- [x] Q&A
- [x] Public release

**Comment by AdrievandeVreede** [comment]
It is now possible to switch between English and Dutch
